Repository trunklabs/gh-contribution-mate, pull requests merged in 2023-01, with the labels that each got.

#16 docs: add contribution rules and code of conduct
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#31 feat: advice to configure gh no-reply email
  src/commands/config/config.ts
Labels: enhancement

#33 feat: read config from the disk
  deno.lock
  import_map.json
  src/commands/config/config.ts
  src/models/config/config.ts
Labels: enhancement

#35 feat: enhance logs with ansi and colors
  src/commands/config/config.ts
  src/main.ts
Labels: enhancement

#38 chore: move import map to deno config file
  deno.jsonc
  import_map.json
Labels: type: chore

#43 chore: sematic pr, issue templates to forms
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/pull_request_template.md
  .github/semantic.yml
Labels: type: chore

#41 refactor: united config usage in config comman
  deno.lock
  src/commands/config/config.ts
  src/models/config/config.ts
  src/models/git/git.ts
  src/models/repository/repository.ts
Labels: type: refactor
